//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TEAM2OIESModel", "FK__Endograft__brand__68D28DBC", "Brand", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TEAM2OIES.Models.DB.Brand), "Endograft", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TEAM2OIES.Models.DB.Endograft), true)]
[assembly: EdmRelationshipAttribute("TEAM2OIESModel", "FK__Endograft__patie__67DE6983", "Patient", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TEAM2OIES.Models.DB.Patient), "Endograft", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TEAM2OIES.Models.DB.Endograft), true)]
[assembly: EdmRelationshipAttribute("TEAM2OIESModel", "FK__Image__seriesId__7167D3BD", "Series", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TEAM2OIES.Models.DB.Series), "Image", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TEAM2OIES.Models.DB.Image), true)]
[assembly: EdmRelationshipAttribute("TEAM2OIESModel", "FK__Surgeon__institu__603D47BB", "Institution", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TEAM2OIES.Models.DB.Institution), "Surgeon", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TEAM2OIES.Models.DB.Surgeon), true)]
[assembly: EdmRelationshipAttribute("TEAM2OIESModel", "FK__Testimoni__surge__7720AD13", "Institution", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TEAM2OIES.Models.DB.Institution), "Testimonials", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TEAM2OIES.Models.DB.Testimonial), true)]
[assembly: EdmRelationshipAttribute("TEAM2OIESModel", "FK__Patient__surgeon__6319B466", "Surgeon", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TEAM2OIES.Models.DB.Surgeon), "Patient", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TEAM2OIES.Models.DB.Patient), true)]
[assembly: EdmRelationshipAttribute("TEAM2OIESModel", "FK__Study__patientId__6BAEFA67", "Patient", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TEAM2OIES.Models.DB.Patient), "Study", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TEAM2OIES.Models.DB.Study), true)]
[assembly: EdmRelationshipAttribute("TEAM2OIESModel", "FK__Series__studyId__6E8B6712", "Study", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TEAM2OIES.Models.DB.Study), "Series", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TEAM2OIES.Models.DB.Series), true)]

#endregion

namespace TEAM2OIES.Models.DB
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TEAM2OIESEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TEAM2OIESEntities1 object using the connection string found in the 'TEAM2OIESEntities1' section of the application configuration file.
        /// </summary>
        public TEAM2OIESEntities1() : base("name=TEAM2OIESEntities1", "TEAM2OIESEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TEAM2OIESEntities1 object.
        /// </summary>
        public TEAM2OIESEntities1(string connectionString) : base(connectionString, "TEAM2OIESEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TEAM2OIESEntities1 object.
        /// </summary>
        public TEAM2OIESEntities1(EntityConnection connection) : base(connection, "TEAM2OIESEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Audit> Audits
        {
            get
            {
                if ((_Audits == null))
                {
                    _Audits = base.CreateObjectSet<Audit>("Audits");
                }
                return _Audits;
            }
        }
        private ObjectSet<Audit> _Audits;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Brand> Brands
        {
            get
            {
                if ((_Brands == null))
                {
                    _Brands = base.CreateObjectSet<Brand>("Brands");
                }
                return _Brands;
            }
        }
        private ObjectSet<Brand> _Brands;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Endograft> Endografts
        {
            get
            {
                if ((_Endografts == null))
                {
                    _Endografts = base.CreateObjectSet<Endograft>("Endografts");
                }
                return _Endografts;
            }
        }
        private ObjectSet<Endograft> _Endografts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Image> Images
        {
            get
            {
                if ((_Images == null))
                {
                    _Images = base.CreateObjectSet<Image>("Images");
                }
                return _Images;
            }
        }
        private ObjectSet<Image> _Images;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Institution> Institutions
        {
            get
            {
                if ((_Institutions == null))
                {
                    _Institutions = base.CreateObjectSet<Institution>("Institutions");
                }
                return _Institutions;
            }
        }
        private ObjectSet<Institution> _Institutions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Patient> Patients
        {
            get
            {
                if ((_Patients == null))
                {
                    _Patients = base.CreateObjectSet<Patient>("Patients");
                }
                return _Patients;
            }
        }
        private ObjectSet<Patient> _Patients;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Series> Series
        {
            get
            {
                if ((_Series == null))
                {
                    _Series = base.CreateObjectSet<Series>("Series");
                }
                return _Series;
            }
        }
        private ObjectSet<Series> _Series;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Study> Studies
        {
            get
            {
                if ((_Studies == null))
                {
                    _Studies = base.CreateObjectSet<Study>("Studies");
                }
                return _Studies;
            }
        }
        private ObjectSet<Study> _Studies;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Surgeon> Surgeons
        {
            get
            {
                if ((_Surgeons == null))
                {
                    _Surgeons = base.CreateObjectSet<Surgeon>("Surgeons");
                }
                return _Surgeons;
            }
        }
        private ObjectSet<Surgeon> _Surgeons;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Testimonial> Testimonials
        {
            get
            {
                if ((_Testimonials == null))
                {
                    _Testimonials = base.CreateObjectSet<Testimonial>("Testimonials");
                }
                return _Testimonials;
            }
        }
        private ObjectSet<Testimonial> _Testimonials;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Audits EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAudits(Audit audit)
        {
            base.AddObject("Audits", audit);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Brands EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBrands(Brand brand)
        {
            base.AddObject("Brands", brand);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Endografts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEndografts(Endograft endograft)
        {
            base.AddObject("Endografts", endograft);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Images EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToImages(Image image)
        {
            base.AddObject("Images", image);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Institutions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInstitutions(Institution institution)
        {
            base.AddObject("Institutions", institution);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Patients EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPatients(Patient patient)
        {
            base.AddObject("Patients", patient);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Series EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSeries(Series series)
        {
            base.AddObject("Series", series);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Studies EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStudies(Study study)
        {
            base.AddObject("Studies", study);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Surgeons EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSurgeons(Surgeon surgeon)
        {
            base.AddObject("Surgeons", surgeon);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Testimonials EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTestimonials(Testimonial testimonial)
        {
            base.AddObject("Testimonials", testimonial);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TEAM2OIESModel", Name="Audit")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Audit : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Audit object.
        /// </summary>
        /// <param name="auditId">Initial value of the auditId property.</param>
        public static Audit CreateAudit(global::System.Int32 auditId)
        {
            Audit audit = new Audit();
            audit.auditId = auditId;
            return audit;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 auditId
        {
            get
            {
                return _auditId;
            }
            set
            {
                if (_auditId != value)
                {
                    OnauditIdChanging(value);
                    ReportPropertyChanging("auditId");
                    _auditId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("auditId");
                    OnauditIdChanged();
                }
            }
        }
        private global::System.Int32 _auditId;
        partial void OnauditIdChanging(global::System.Int32 value);
        partial void OnauditIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> auditUserId
        {
            get
            {
                return _auditUserId;
            }
            set
            {
                OnauditUserIdChanging(value);
                ReportPropertyChanging("auditUserId");
                _auditUserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("auditUserId");
                OnauditUserIdChanged();
            }
        }
        private Nullable<global::System.Int32> _auditUserId;
        partial void OnauditUserIdChanging(Nullable<global::System.Int32> value);
        partial void OnauditUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String auditUsername
        {
            get
            {
                return _auditUsername;
            }
            set
            {
                OnauditUsernameChanging(value);
                ReportPropertyChanging("auditUsername");
                _auditUsername = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("auditUsername");
                OnauditUsernameChanged();
            }
        }
        private global::System.String _auditUsername;
        partial void OnauditUsernameChanging(global::System.String value);
        partial void OnauditUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> auditDate
        {
            get
            {
                return _auditDate;
            }
            set
            {
                OnauditDateChanging(value);
                ReportPropertyChanging("auditDate");
                _auditDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("auditDate");
                OnauditDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _auditDate;
        partial void OnauditDateChanging(Nullable<global::System.DateTime> value);
        partial void OnauditDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> auditTable
        {
            get
            {
                return _auditTable;
            }
            set
            {
                OnauditTableChanging(value);
                ReportPropertyChanging("auditTable");
                _auditTable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("auditTable");
                OnauditTableChanged();
            }
        }
        private Nullable<global::System.Int32> _auditTable;
        partial void OnauditTableChanging(Nullable<global::System.Int32> value);
        partial void OnauditTableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String access
        {
            get
            {
                return _access;
            }
            set
            {
                OnaccessChanging(value);
                ReportPropertyChanging("access");
                _access = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("access");
                OnaccessChanged();
            }
        }
        private global::System.String _access;
        partial void OnaccessChanging(global::System.String value);
        partial void OnaccessChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TEAM2OIESModel", Name="Brand")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Brand : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Brand object.
        /// </summary>
        /// <param name="brandId">Initial value of the brandId property.</param>
        public static Brand CreateBrand(global::System.Int32 brandId)
        {
            Brand brand = new Brand();
            brand.brandId = brandId;
            return brand;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 brandId
        {
            get
            {
                return _brandId;
            }
            set
            {
                if (_brandId != value)
                {
                    OnbrandIdChanging(value);
                    ReportPropertyChanging("brandId");
                    _brandId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("brandId");
                    OnbrandIdChanged();
                }
            }
        }
        private global::System.Int32 _brandId;
        partial void OnbrandIdChanging(global::System.Int32 value);
        partial void OnbrandIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String brandName
        {
            get
            {
                return _brandName;
            }
            set
            {
                OnbrandNameChanging(value);
                ReportPropertyChanging("brandName");
                _brandName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("brandName");
                OnbrandNameChanged();
            }
        }
        private global::System.String _brandName;
        partial void OnbrandNameChanging(global::System.String value);
        partial void OnbrandNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TEAM2OIESModel", "FK__Endograft__brand__68D28DBC", "Endograft")]
        public EntityCollection<Endograft> Endografts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Endograft>("TEAM2OIESModel.FK__Endograft__brand__68D28DBC", "Endograft");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Endograft>("TEAM2OIESModel.FK__Endograft__brand__68D28DBC", "Endograft", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TEAM2OIESModel", Name="Endograft")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Endograft : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Endograft object.
        /// </summary>
        /// <param name="endograftId">Initial value of the endograftId property.</param>
        public static Endograft CreateEndograft(global::System.Int32 endograftId)
        {
            Endograft endograft = new Endograft();
            endograft.endograftId = endograftId;
            return endograft;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 endograftId
        {
            get
            {
                return _endograftId;
            }
            set
            {
                if (_endograftId != value)
                {
                    OnendograftIdChanging(value);
                    ReportPropertyChanging("endograftId");
                    _endograftId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("endograftId");
                    OnendograftIdChanged();
                }
            }
        }
        private global::System.Int32 _endograftId;
        partial void OnendograftIdChanging(global::System.Int32 value);
        partial void OnendograftIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> patientId
        {
            get
            {
                return _patientId;
            }
            set
            {
                OnpatientIdChanging(value);
                ReportPropertyChanging("patientId");
                _patientId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("patientId");
                OnpatientIdChanged();
            }
        }
        private Nullable<global::System.Int32> _patientId;
        partial void OnpatientIdChanging(Nullable<global::System.Int32> value);
        partial void OnpatientIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> brandId
        {
            get
            {
                return _brandId;
            }
            set
            {
                OnbrandIdChanging(value);
                ReportPropertyChanging("brandId");
                _brandId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("brandId");
                OnbrandIdChanged();
            }
        }
        private Nullable<global::System.Int32> _brandId;
        partial void OnbrandIdChanging(Nullable<global::System.Int32> value);
        partial void OnbrandIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> diameter
        {
            get
            {
                return _diameter;
            }
            set
            {
                OndiameterChanging(value);
                ReportPropertyChanging("diameter");
                _diameter = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("diameter");
                OndiameterChanged();
            }
        }
        private Nullable<global::System.Single> _diameter;
        partial void OndiameterChanging(Nullable<global::System.Single> value);
        partial void OndiameterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> length
        {
            get
            {
                return _length;
            }
            set
            {
                OnlengthChanging(value);
                ReportPropertyChanging("length");
                _length = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("length");
                OnlengthChanged();
            }
        }
        private Nullable<global::System.Single> _length;
        partial void OnlengthChanging(Nullable<global::System.Single> value);
        partial void OnlengthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> entryPoint
        {
            get
            {
                return _entryPoint;
            }
            set
            {
                OnentryPointChanging(value);
                ReportPropertyChanging("entryPoint");
                _entryPoint = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("entryPoint");
                OnentryPointChanged();
            }
        }
        private Nullable<global::System.Single> _entryPoint;
        partial void OnentryPointChanging(Nullable<global::System.Single> value);
        partial void OnentryPointChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> unilateralLegLength
        {
            get
            {
                return _unilateralLegLength;
            }
            set
            {
                OnunilateralLegLengthChanging(value);
                ReportPropertyChanging("unilateralLegLength");
                _unilateralLegLength = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("unilateralLegLength");
                OnunilateralLegLengthChanged();
            }
        }
        private Nullable<global::System.Single> _unilateralLegLength;
        partial void OnunilateralLegLengthChanging(Nullable<global::System.Single> value);
        partial void OnunilateralLegLengthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> controlaterLegDiameter
        {
            get
            {
                return _controlaterLegDiameter;
            }
            set
            {
                OncontrolaterLegDiameterChanging(value);
                ReportPropertyChanging("controlaterLegDiameter");
                _controlaterLegDiameter = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("controlaterLegDiameter");
                OncontrolaterLegDiameterChanged();
            }
        }
        private Nullable<global::System.Single> _controlaterLegDiameter;
        partial void OncontrolaterLegDiameterChanging(Nullable<global::System.Single> value);
        partial void OncontrolaterLegDiameterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> controlaterLegLength
        {
            get
            {
                return _controlaterLegLength;
            }
            set
            {
                OncontrolaterLegLengthChanging(value);
                ReportPropertyChanging("controlaterLegLength");
                _controlaterLegLength = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("controlaterLegLength");
                OncontrolaterLegLengthChanged();
            }
        }
        private Nullable<global::System.Single> _controlaterLegLength;
        partial void OncontrolaterLegLengthChanging(Nullable<global::System.Single> value);
        partial void OncontrolaterLegLengthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> unilateralLegDiameter
        {
            get
            {
                return _unilateralLegDiameter;
            }
            set
            {
                OnunilateralLegDiameterChanging(value);
                ReportPropertyChanging("unilateralLegDiameter");
                _unilateralLegDiameter = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("unilateralLegDiameter");
                OnunilateralLegDiameterChanged();
            }
        }
        private Nullable<global::System.Single> _unilateralLegDiameter;
        partial void OnunilateralLegDiameterChanging(Nullable<global::System.Single> value);
        partial void OnunilateralLegDiameterChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TEAM2OIESModel", "FK__Endograft__brand__68D28DBC", "Brand")]
        public Brand Brand
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Brand>("TEAM2OIESModel.FK__Endograft__brand__68D28DBC", "Brand").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Brand>("TEAM2OIESModel.FK__Endograft__brand__68D28DBC", "Brand").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Brand> BrandReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Brand>("TEAM2OIESModel.FK__Endograft__brand__68D28DBC", "Brand");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Brand>("TEAM2OIESModel.FK__Endograft__brand__68D28DBC", "Brand", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TEAM2OIESModel", "FK__Endograft__patie__67DE6983", "Patient")]
        public Patient Patient
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Patient>("TEAM2OIESModel.FK__Endograft__patie__67DE6983", "Patient").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Patient>("TEAM2OIESModel.FK__Endograft__patie__67DE6983", "Patient").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Patient> PatientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Patient>("TEAM2OIESModel.FK__Endograft__patie__67DE6983", "Patient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Patient>("TEAM2OIESModel.FK__Endograft__patie__67DE6983", "Patient", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TEAM2OIESModel", Name="Image")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Image : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Image object.
        /// </summary>
        /// <param name="imageId">Initial value of the imageId property.</param>
        public static Image CreateImage(global::System.Int32 imageId)
        {
            Image image = new Image();
            image.imageId = imageId;
            return image;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 imageId
        {
            get
            {
                return _imageId;
            }
            set
            {
                if (_imageId != value)
                {
                    OnimageIdChanging(value);
                    ReportPropertyChanging("imageId");
                    _imageId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("imageId");
                    OnimageIdChanged();
                }
            }
        }
        private global::System.Int32 _imageId;
        partial void OnimageIdChanging(global::System.Int32 value);
        partial void OnimageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> seriesId
        {
            get
            {
                return _seriesId;
            }
            set
            {
                OnseriesIdChanging(value);
                ReportPropertyChanging("seriesId");
                _seriesId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("seriesId");
                OnseriesIdChanged();
            }
        }
        private Nullable<global::System.Int32> _seriesId;
        partial void OnseriesIdChanging(Nullable<global::System.Int32> value);
        partial void OnseriesIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> imageOrder
        {
            get
            {
                return _imageOrder;
            }
            set
            {
                OnimageOrderChanging(value);
                ReportPropertyChanging("imageOrder");
                _imageOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("imageOrder");
                OnimageOrderChanged();
            }
        }
        private Nullable<global::System.Int32> _imageOrder;
        partial void OnimageOrderChanging(Nullable<global::System.Int32> value);
        partial void OnimageOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String imageFilename
        {
            get
            {
                return _imageFilename;
            }
            set
            {
                OnimageFilenameChanging(value);
                ReportPropertyChanging("imageFilename");
                _imageFilename = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("imageFilename");
                OnimageFilenameChanged();
            }
        }
        private global::System.String _imageFilename;
        partial void OnimageFilenameChanging(global::System.String value);
        partial void OnimageFilenameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String imageTitle
        {
            get
            {
                return _imageTitle;
            }
            set
            {
                OnimageTitleChanging(value);
                ReportPropertyChanging("imageTitle");
                _imageTitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("imageTitle");
                OnimageTitleChanged();
            }
        }
        private global::System.String _imageTitle;
        partial void OnimageTitleChanging(global::System.String value);
        partial void OnimageTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> sliceThickness
        {
            get
            {
                return _sliceThickness;
            }
            set
            {
                OnsliceThicknessChanging(value);
                ReportPropertyChanging("sliceThickness");
                _sliceThickness = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sliceThickness");
                OnsliceThicknessChanged();
            }
        }
        private Nullable<global::System.Single> _sliceThickness;
        partial void OnsliceThicknessChanging(Nullable<global::System.Single> value);
        partial void OnsliceThicknessChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> pixelSize
        {
            get
            {
                return _pixelSize;
            }
            set
            {
                OnpixelSizeChanging(value);
                ReportPropertyChanging("pixelSize");
                _pixelSize = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pixelSize");
                OnpixelSizeChanged();
            }
        }
        private Nullable<global::System.Single> _pixelSize;
        partial void OnpixelSizeChanging(Nullable<global::System.Single> value);
        partial void OnpixelSizeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TEAM2OIESModel", "FK__Image__seriesId__7167D3BD", "Series")]
        public Series Series
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Series>("TEAM2OIESModel.FK__Image__seriesId__7167D3BD", "Series").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Series>("TEAM2OIESModel.FK__Image__seriesId__7167D3BD", "Series").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Series> SeriesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Series>("TEAM2OIESModel.FK__Image__seriesId__7167D3BD", "Series");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Series>("TEAM2OIESModel.FK__Image__seriesId__7167D3BD", "Series", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TEAM2OIESModel", Name="Institution")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Institution : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Institution object.
        /// </summary>
        /// <param name="institutionId">Initial value of the institutionId property.</param>
        public static Institution CreateInstitution(global::System.Int32 institutionId)
        {
            Institution institution = new Institution();
            institution.institutionId = institutionId;
            return institution;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 institutionId
        {
            get
            {
                return _institutionId;
            }
            set
            {
                if (_institutionId != value)
                {
                    OninstitutionIdChanging(value);
                    ReportPropertyChanging("institutionId");
                    _institutionId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("institutionId");
                    OninstitutionIdChanged();
                }
            }
        }
        private global::System.Int32 _institutionId;
        partial void OninstitutionIdChanging(global::System.Int32 value);
        partial void OninstitutionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String institutionName
        {
            get
            {
                return _institutionName;
            }
            set
            {
                OninstitutionNameChanging(value);
                ReportPropertyChanging("institutionName");
                _institutionName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("institutionName");
                OninstitutionNameChanged();
            }
        }
        private global::System.String _institutionName;
        partial void OninstitutionNameChanging(global::System.String value);
        partial void OninstitutionNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String institutionLocation
        {
            get
            {
                return _institutionLocation;
            }
            set
            {
                OninstitutionLocationChanging(value);
                ReportPropertyChanging("institutionLocation");
                _institutionLocation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("institutionLocation");
                OninstitutionLocationChanged();
            }
        }
        private global::System.String _institutionLocation;
        partial void OninstitutionLocationChanging(global::System.String value);
        partial void OninstitutionLocationChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TEAM2OIESModel", "FK__Surgeon__institu__603D47BB", "Surgeon")]
        public EntityCollection<Surgeon> Surgeons
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Surgeon>("TEAM2OIESModel.FK__Surgeon__institu__603D47BB", "Surgeon");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Surgeon>("TEAM2OIESModel.FK__Surgeon__institu__603D47BB", "Surgeon", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TEAM2OIESModel", "FK__Testimoni__surge__7720AD13", "Testimonials")]
        public EntityCollection<Testimonial> Testimonials
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Testimonial>("TEAM2OIESModel.FK__Testimoni__surge__7720AD13", "Testimonials");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Testimonial>("TEAM2OIESModel.FK__Testimoni__surge__7720AD13", "Testimonials", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TEAM2OIESModel", Name="Patient")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Patient : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Patient object.
        /// </summary>
        /// <param name="patientId">Initial value of the patientId property.</param>
        public static Patient CreatePatient(global::System.Int32 patientId)
        {
            Patient patient = new Patient();
            patient.patientId = patientId;
            return patient;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 patientId
        {
            get
            {
                return _patientId;
            }
            set
            {
                if (_patientId != value)
                {
                    OnpatientIdChanging(value);
                    ReportPropertyChanging("patientId");
                    _patientId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("patientId");
                    OnpatientIdChanged();
                }
            }
        }
        private global::System.Int32 _patientId;
        partial void OnpatientIdChanging(global::System.Int32 value);
        partial void OnpatientIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> surgeonId
        {
            get
            {
                return _surgeonId;
            }
            set
            {
                OnsurgeonIdChanging(value);
                ReportPropertyChanging("surgeonId");
                _surgeonId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("surgeonId");
                OnsurgeonIdChanged();
            }
        }
        private Nullable<global::System.Int32> _surgeonId;
        partial void OnsurgeonIdChanging(Nullable<global::System.Int32> value);
        partial void OnsurgeonIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> originalId
        {
            get
            {
                return _originalId;
            }
            set
            {
                OnoriginalIdChanging(value);
                ReportPropertyChanging("originalId");
                _originalId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("originalId");
                OnoriginalIdChanged();
            }
        }
        private Nullable<global::System.Int32> _originalId;
        partial void OnoriginalIdChanging(Nullable<global::System.Int32> value);
        partial void OnoriginalIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sex
        {
            get
            {
                return _sex;
            }
            set
            {
                OnsexChanging(value);
                ReportPropertyChanging("sex");
                _sex = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sex");
                OnsexChanged();
            }
        }
        private global::System.String _sex;
        partial void OnsexChanging(global::System.String value);
        partial void OnsexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> age
        {
            get
            {
                return _age;
            }
            set
            {
                OnageChanging(value);
                ReportPropertyChanging("age");
                _age = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("age");
                OnageChanged();
            }
        }
        private Nullable<global::System.Int32> _age;
        partial void OnageChanging(Nullable<global::System.Int32> value);
        partial void OnageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String entryDate
        {
            get
            {
                return _entryDate;
            }
            set
            {
                OnentryDateChanging(value);
                ReportPropertyChanging("entryDate");
                _entryDate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("entryDate");
                OnentryDateChanged();
            }
        }
        private global::System.String _entryDate;
        partial void OnentryDateChanging(global::System.String value);
        partial void OnentryDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dateOfSurgery
        {
            get
            {
                return _dateOfSurgery;
            }
            set
            {
                OndateOfSurgeryChanging(value);
                ReportPropertyChanging("dateOfSurgery");
                _dateOfSurgery = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dateOfSurgery");
                OndateOfSurgeryChanged();
            }
        }
        private global::System.String _dateOfSurgery;
        partial void OndateOfSurgeryChanging(global::System.String value);
        partial void OndateOfSurgeryChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TEAM2OIESModel", "FK__Endograft__patie__67DE6983", "Endograft")]
        public EntityCollection<Endograft> Endografts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Endograft>("TEAM2OIESModel.FK__Endograft__patie__67DE6983", "Endograft");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Endograft>("TEAM2OIESModel.FK__Endograft__patie__67DE6983", "Endograft", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TEAM2OIESModel", "FK__Patient__surgeon__6319B466", "Surgeon")]
        public Surgeon Surgeon
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Surgeon>("TEAM2OIESModel.FK__Patient__surgeon__6319B466", "Surgeon").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Surgeon>("TEAM2OIESModel.FK__Patient__surgeon__6319B466", "Surgeon").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Surgeon> SurgeonReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Surgeon>("TEAM2OIESModel.FK__Patient__surgeon__6319B466", "Surgeon");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Surgeon>("TEAM2OIESModel.FK__Patient__surgeon__6319B466", "Surgeon", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TEAM2OIESModel", "FK__Study__patientId__6BAEFA67", "Study")]
        public EntityCollection<Study> Studies
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Study>("TEAM2OIESModel.FK__Study__patientId__6BAEFA67", "Study");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Study>("TEAM2OIESModel.FK__Study__patientId__6BAEFA67", "Study", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TEAM2OIESModel", Name="Series")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Series : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Series object.
        /// </summary>
        /// <param name="seriesId">Initial value of the seriesId property.</param>
        public static Series CreateSeries(global::System.Int32 seriesId)
        {
            Series series = new Series();
            series.seriesId = seriesId;
            return series;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 seriesId
        {
            get
            {
                return _seriesId;
            }
            set
            {
                if (_seriesId != value)
                {
                    OnseriesIdChanging(value);
                    ReportPropertyChanging("seriesId");
                    _seriesId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("seriesId");
                    OnseriesIdChanged();
                }
            }
        }
        private global::System.Int32 _seriesId;
        partial void OnseriesIdChanging(global::System.Int32 value);
        partial void OnseriesIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> studyId
        {
            get
            {
                return _studyId;
            }
            set
            {
                OnstudyIdChanging(value);
                ReportPropertyChanging("studyId");
                _studyId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("studyId");
                OnstudyIdChanged();
            }
        }
        private Nullable<global::System.Int32> _studyId;
        partial void OnstudyIdChanging(Nullable<global::System.Int32> value);
        partial void OnstudyIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> originalSeriesId
        {
            get
            {
                return _originalSeriesId;
            }
            set
            {
                OnoriginalSeriesIdChanging(value);
                ReportPropertyChanging("originalSeriesId");
                _originalSeriesId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("originalSeriesId");
                OnoriginalSeriesIdChanged();
            }
        }
        private Nullable<global::System.Int32> _originalSeriesId;
        partial void OnoriginalSeriesIdChanging(Nullable<global::System.Int32> value);
        partial void OnoriginalSeriesIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String seriesDescription
        {
            get
            {
                return _seriesDescription;
            }
            set
            {
                OnseriesDescriptionChanging(value);
                ReportPropertyChanging("seriesDescription");
                _seriesDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("seriesDescription");
                OnseriesDescriptionChanged();
            }
        }
        private global::System.String _seriesDescription;
        partial void OnseriesDescriptionChanging(global::System.String value);
        partial void OnseriesDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String seriesDate
        {
            get
            {
                return _seriesDate;
            }
            set
            {
                OnseriesDateChanging(value);
                ReportPropertyChanging("seriesDate");
                _seriesDate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("seriesDate");
                OnseriesDateChanged();
            }
        }
        private global::System.String _seriesDate;
        partial void OnseriesDateChanging(global::System.String value);
        partial void OnseriesDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> totalNumberOfSlices
        {
            get
            {
                return _totalNumberOfSlices;
            }
            set
            {
                OntotalNumberOfSlicesChanging(value);
                ReportPropertyChanging("totalNumberOfSlices");
                _totalNumberOfSlices = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("totalNumberOfSlices");
                OntotalNumberOfSlicesChanged();
            }
        }
        private Nullable<global::System.Int32> _totalNumberOfSlices;
        partial void OntotalNumberOfSlicesChanging(Nullable<global::System.Int32> value);
        partial void OntotalNumberOfSlicesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ROIBegin
        {
            get
            {
                return _ROIBegin;
            }
            set
            {
                OnROIBeginChanging(value);
                ReportPropertyChanging("ROIBegin");
                _ROIBegin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ROIBegin");
                OnROIBeginChanged();
            }
        }
        private Nullable<global::System.Int32> _ROIBegin;
        partial void OnROIBeginChanging(Nullable<global::System.Int32> value);
        partial void OnROIBeginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> illiacBif
        {
            get
            {
                return _illiacBif;
            }
            set
            {
                OnilliacBifChanging(value);
                ReportPropertyChanging("illiacBif");
                _illiacBif = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("illiacBif");
                OnilliacBifChanged();
            }
        }
        private Nullable<global::System.Single> _illiacBif;
        partial void OnilliacBifChanging(Nullable<global::System.Single> value);
        partial void OnilliacBifChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String comments
        {
            get
            {
                return _comments;
            }
            set
            {
                OncommentsChanging(value);
                ReportPropertyChanging("comments");
                _comments = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("comments");
                OncommentsChanged();
            }
        }
        private global::System.String _comments;
        partial void OncommentsChanging(global::System.String value);
        partial void OncommentsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ROIEnd
        {
            get
            {
                return _ROIEnd;
            }
            set
            {
                OnROIEndChanging(value);
                ReportPropertyChanging("ROIEnd");
                _ROIEnd = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ROIEnd");
                OnROIEndChanged();
            }
        }
        private Nullable<global::System.Int32> _ROIEnd;
        partial void OnROIEndChanging(Nullable<global::System.Int32> value);
        partial void OnROIEndChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> totalSlicesInROI
        {
            get
            {
                return _totalSlicesInROI;
            }
            set
            {
                OntotalSlicesInROIChanging(value);
                ReportPropertyChanging("totalSlicesInROI");
                _totalSlicesInROI = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("totalSlicesInROI");
                OntotalSlicesInROIChanged();
            }
        }
        private Nullable<global::System.Int32> _totalSlicesInROI;
        partial void OntotalSlicesInROIChanging(Nullable<global::System.Int32> value);
        partial void OntotalSlicesInROIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> lengthROIINcm
        {
            get
            {
                return _lengthROIINcm;
            }
            set
            {
                OnlengthROIINcmChanging(value);
                ReportPropertyChanging("lengthROIINcm");
                _lengthROIINcm = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lengthROIINcm");
                OnlengthROIINcmChanged();
            }
        }
        private Nullable<global::System.Single> _lengthROIINcm;
        partial void OnlengthROIINcmChanging(Nullable<global::System.Single> value);
        partial void OnlengthROIINcmChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TEAM2OIESModel", "FK__Image__seriesId__7167D3BD", "Image")]
        public EntityCollection<Image> Images
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Image>("TEAM2OIESModel.FK__Image__seriesId__7167D3BD", "Image");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Image>("TEAM2OIESModel.FK__Image__seriesId__7167D3BD", "Image", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TEAM2OIESModel", "FK__Series__studyId__6E8B6712", "Study")]
        public Study Study
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Study>("TEAM2OIESModel.FK__Series__studyId__6E8B6712", "Study").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Study>("TEAM2OIESModel.FK__Series__studyId__6E8B6712", "Study").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Study> StudyReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Study>("TEAM2OIESModel.FK__Series__studyId__6E8B6712", "Study");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Study>("TEAM2OIESModel.FK__Series__studyId__6E8B6712", "Study", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TEAM2OIESModel", Name="Study")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Study : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Study object.
        /// </summary>
        /// <param name="studyId">Initial value of the studyId property.</param>
        public static Study CreateStudy(global::System.Int32 studyId)
        {
            Study study = new Study();
            study.studyId = studyId;
            return study;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 studyId
        {
            get
            {
                return _studyId;
            }
            set
            {
                if (_studyId != value)
                {
                    OnstudyIdChanging(value);
                    ReportPropertyChanging("studyId");
                    _studyId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("studyId");
                    OnstudyIdChanged();
                }
            }
        }
        private global::System.Int32 _studyId;
        partial void OnstudyIdChanging(global::System.Int32 value);
        partial void OnstudyIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> patientId
        {
            get
            {
                return _patientId;
            }
            set
            {
                OnpatientIdChanging(value);
                ReportPropertyChanging("patientId");
                _patientId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("patientId");
                OnpatientIdChanged();
            }
        }
        private Nullable<global::System.Int32> _patientId;
        partial void OnpatientIdChanging(Nullable<global::System.Int32> value);
        partial void OnpatientIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> originalStudyId
        {
            get
            {
                return _originalStudyId;
            }
            set
            {
                OnoriginalStudyIdChanging(value);
                ReportPropertyChanging("originalStudyId");
                _originalStudyId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("originalStudyId");
                OnoriginalStudyIdChanged();
            }
        }
        private Nullable<global::System.Int32> _originalStudyId;
        partial void OnoriginalStudyIdChanging(Nullable<global::System.Int32> value);
        partial void OnoriginalStudyIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String studyDescription
        {
            get
            {
                return _studyDescription;
            }
            set
            {
                OnstudyDescriptionChanging(value);
                ReportPropertyChanging("studyDescription");
                _studyDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("studyDescription");
                OnstudyDescriptionChanged();
            }
        }
        private global::System.String _studyDescription;
        partial void OnstudyDescriptionChanging(global::System.String value);
        partial void OnstudyDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String studyDate
        {
            get
            {
                return _studyDate;
            }
            set
            {
                OnstudyDateChanging(value);
                ReportPropertyChanging("studyDate");
                _studyDate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("studyDate");
                OnstudyDateChanged();
            }
        }
        private global::System.String _studyDate;
        partial void OnstudyDateChanging(global::System.String value);
        partial void OnstudyDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CT
        {
            get
            {
                return _CT;
            }
            set
            {
                OnCTChanging(value);
                ReportPropertyChanging("CT");
                _CT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CT");
                OnCTChanged();
            }
        }
        private Nullable<global::System.Int32> _CT;
        partial void OnCTChanging(Nullable<global::System.Int32> value);
        partial void OnCTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> delay
        {
            get
            {
                return _delay;
            }
            set
            {
                OndelayChanging(value);
                ReportPropertyChanging("delay");
                _delay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("delay");
                OndelayChanged();
            }
        }
        private Nullable<global::System.Single> _delay;
        partial void OndelayChanging(Nullable<global::System.Single> value);
        partial void OndelayChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TEAM2OIESModel", "FK__Study__patientId__6BAEFA67", "Patient")]
        public Patient Patient
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Patient>("TEAM2OIESModel.FK__Study__patientId__6BAEFA67", "Patient").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Patient>("TEAM2OIESModel.FK__Study__patientId__6BAEFA67", "Patient").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Patient> PatientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Patient>("TEAM2OIESModel.FK__Study__patientId__6BAEFA67", "Patient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Patient>("TEAM2OIESModel.FK__Study__patientId__6BAEFA67", "Patient", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TEAM2OIESModel", "FK__Series__studyId__6E8B6712", "Series")]
        public EntityCollection<Series> Series
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Series>("TEAM2OIESModel.FK__Series__studyId__6E8B6712", "Series");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Series>("TEAM2OIESModel.FK__Series__studyId__6E8B6712", "Series", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TEAM2OIESModel", Name="Surgeon")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Surgeon : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Surgeon object.
        /// </summary>
        /// <param name="surgeonId">Initial value of the surgeonId property.</param>
        public static Surgeon CreateSurgeon(global::System.Int32 surgeonId)
        {
            Surgeon surgeon = new Surgeon();
            surgeon.surgeonId = surgeonId;
            return surgeon;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 surgeonId
        {
            get
            {
                return _surgeonId;
            }
            set
            {
                if (_surgeonId != value)
                {
                    OnsurgeonIdChanging(value);
                    ReportPropertyChanging("surgeonId");
                    _surgeonId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("surgeonId");
                    OnsurgeonIdChanged();
                }
            }
        }
        private global::System.Int32 _surgeonId;
        partial void OnsurgeonIdChanging(global::System.Int32 value);
        partial void OnsurgeonIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> institutionId
        {
            get
            {
                return _institutionId;
            }
            set
            {
                OninstitutionIdChanging(value);
                ReportPropertyChanging("institutionId");
                _institutionId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("institutionId");
                OninstitutionIdChanged();
            }
        }
        private Nullable<global::System.Int32> _institutionId;
        partial void OninstitutionIdChanging(Nullable<global::System.Int32> value);
        partial void OninstitutionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String firstName
        {
            get
            {
                return _firstName;
            }
            set
            {
                OnfirstNameChanging(value);
                ReportPropertyChanging("firstName");
                _firstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("firstName");
                OnfirstNameChanged();
            }
        }
        private global::System.String _firstName;
        partial void OnfirstNameChanging(global::System.String value);
        partial void OnfirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lastName
        {
            get
            {
                return _lastName;
            }
            set
            {
                OnlastNameChanging(value);
                ReportPropertyChanging("lastName");
                _lastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("lastName");
                OnlastNameChanged();
            }
        }
        private global::System.String _lastName;
        partial void OnlastNameChanging(global::System.String value);
        partial void OnlastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TEAM2OIESModel", "FK__Surgeon__institu__603D47BB", "Institution")]
        public Institution Institution
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Institution>("TEAM2OIESModel.FK__Surgeon__institu__603D47BB", "Institution").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Institution>("TEAM2OIESModel.FK__Surgeon__institu__603D47BB", "Institution").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Institution> InstitutionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Institution>("TEAM2OIESModel.FK__Surgeon__institu__603D47BB", "Institution");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Institution>("TEAM2OIESModel.FK__Surgeon__institu__603D47BB", "Institution", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TEAM2OIESModel", "FK__Patient__surgeon__6319B466", "Patient")]
        public EntityCollection<Patient> Patients
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Patient>("TEAM2OIESModel.FK__Patient__surgeon__6319B466", "Patient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Patient>("TEAM2OIESModel.FK__Patient__surgeon__6319B466", "Patient", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TEAM2OIESModel", Name="Testimonial")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Testimonial : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Testimonial object.
        /// </summary>
        /// <param name="testimonialId">Initial value of the testimonialId property.</param>
        public static Testimonial CreateTestimonial(global::System.Int32 testimonialId)
        {
            Testimonial testimonial = new Testimonial();
            testimonial.testimonialId = testimonialId;
            return testimonial;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 testimonialId
        {
            get
            {
                return _testimonialId;
            }
            set
            {
                if (_testimonialId != value)
                {
                    OntestimonialIdChanging(value);
                    ReportPropertyChanging("testimonialId");
                    _testimonialId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("testimonialId");
                    OntestimonialIdChanged();
                }
            }
        }
        private global::System.Int32 _testimonialId;
        partial void OntestimonialIdChanging(global::System.Int32 value);
        partial void OntestimonialIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String testimonialContent
        {
            get
            {
                return _testimonialContent;
            }
            set
            {
                OntestimonialContentChanging(value);
                ReportPropertyChanging("testimonialContent");
                _testimonialContent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("testimonialContent");
                OntestimonialContentChanged();
            }
        }
        private global::System.String _testimonialContent;
        partial void OntestimonialContentChanging(global::System.String value);
        partial void OntestimonialContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String testimonialDate
        {
            get
            {
                return _testimonialDate;
            }
            set
            {
                OntestimonialDateChanging(value);
                ReportPropertyChanging("testimonialDate");
                _testimonialDate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("testimonialDate");
                OntestimonialDateChanged();
            }
        }
        private global::System.String _testimonialDate;
        partial void OntestimonialDateChanging(global::System.String value);
        partial void OntestimonialDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> surgeonId
        {
            get
            {
                return _surgeonId;
            }
            set
            {
                OnsurgeonIdChanging(value);
                ReportPropertyChanging("surgeonId");
                _surgeonId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("surgeonId");
                OnsurgeonIdChanged();
            }
        }
        private Nullable<global::System.Int32> _surgeonId;
        partial void OnsurgeonIdChanging(Nullable<global::System.Int32> value);
        partial void OnsurgeonIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TEAM2OIESModel", "FK__Testimoni__surge__7720AD13", "Institution")]
        public Institution Institution
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Institution>("TEAM2OIESModel.FK__Testimoni__surge__7720AD13", "Institution").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Institution>("TEAM2OIESModel.FK__Testimoni__surge__7720AD13", "Institution").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Institution> InstitutionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Institution>("TEAM2OIESModel.FK__Testimoni__surge__7720AD13", "Institution");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Institution>("TEAM2OIESModel.FK__Testimoni__surge__7720AD13", "Institution", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
